# Workflow name
name: Daily Links Processor

# --- Triggers ---
on:
  schedule:
    # Runs at 23:16 UTC, which corresponds to 2:46 AM in Iran Standard Time (IRST, UTC+3:30).
    - cron: '16 23 * * *'
  
  workflow_dispatch:

# --- Jobs ---
jobs:
  process-links:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # NEW Step 3: Install Google Chrome and System Dependencies
      # Selenium requires a browser and its driver. This step installs the Chrome browser itself.
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # Step 4: Install Python dependencies (including Selenium)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Run the advanced Python script
      # This now runs the Selenium-based script which controls the installed Chrome browser.
      - name: Run link processing script
        run: python process_links.py

      # Step 6: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add .
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit."
          else
            git commit -m "Automated update: $(date -u)"
            git push
          fi
